name: Package Chrome Extension
on:
  workflow_dispatch:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bundle Extension ZIP
        run: |
          mkdir -p dist
          zip -r "dist/chrome-extension.zip" . -x "*.git*" -x "*.github*" -x "dist/*" -x "node_modules/*"
      - uses: actions/upload-artifact@v4
        with:
          name: Chrome-Extension-v1.0.0
          path: dist/*.zip
          if-no-files-found: error